# Generated by Django 2.2.4 on 2019-09-02 05:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('writer', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=120)),
                ('hit', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('post_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('filename', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('filesize', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('ratings_up', models.IntegerField(default=0)),
                ('ratings_down', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('image_thumbnail', imagekit.models.fields.ProcessedImageField(null=True, upload_to='media/thumbnail')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('board_idx', models.IntegerField()),
                ('writer', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('post_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('vote', models.IntegerField()),
                ('ratings_up', models.IntegerField(default=0)),
                ('ratings_down', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('filename', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('filesize', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('evidence', models.BooleanField(default=False)),
                ('image', models.ImageField(default='media/default.jpg', upload_to='media/images')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64)),
                ('profile_photo', models.ImageField(blank=True, upload_to='')),
                ('name', models.CharField(default='', max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_commentlist', models.ManyToManyField(blank=True, related_name='user_commentlist', to='MECboard.Comment')),
                ('user_likelist', models.ManyToManyField(blank=True, related_name='user_likelist', to='MECboard.Comment')),
            ],
        ),
    ]
